from __future__ import annotations

def token_frequencies(texts: list[str], model: str) -> dict[str, int]: ...
def prefetch_tokenizer(model_id: str) -> None: ...
def loaded_tokenizers() -> list[str]: ...
def prefetch_embedder(repo_id: str | None = ...) -> None: ...
def loaded_embedders() -> list[str]: ...
