def compiled_features() -> frozenset[str]: ...
def token_frequencies(series: object, model: str) -> dict[str, int]: ...
def project_topic_modeling_context(context: bytes, cluster_count: int) -> str: ...
def project_topic_modeling_basis(
    context: bytes, cluster_count: int, corpus_sizes: list[int]
) -> str: ...
