from __future__ import annotations

def token_frequencies(texts: list[str]) -> dict[str, int]: ...
def prefetch_tokenizer(model_id: str) -> None: ...
def loaded_tokenizers() -> list[str]: ...
def list_source_paths(path: str) -> list[str]: ...
def replace_source_paths(path: str, mapper: dict[str, str]) -> int: ...
